### ISSUE TITLE
Failure to run on Windows 10

### ISSUE THREAD

**Issue by mrmarten** [arex18/rocket-lander#2]
Even when i have installed all your Prerequisites i still get this error.

`(base) C:\Users\marte>C:/ProgramData/Anaconda3/python.exe c:/DEV/rocket-lander-master/main_simulation.py
?[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.?[0m
Traceback (most recent call last):
  File "c:/DEV/rocket-lander-master/main_simulation.py", line 20, in <module>
    s = env.reset()
  File "c:\dev\openai\gym\gym\core.py", line 70, in reset
    raise NotImplementedError
NotImplementedError`

**Comment by arex18** [comment]
This [answer](https://github.com/openai/gym/issues/868) should help you. For documentation purposes:
"...can be solved by given the appropriate dtype when initiating Box object. For example:

spaces.Box(..., dtype=np.float32)"

Make sure you installed the right version of the library, using Python 3.x (tested on 3.6).

**Comment by arex18** [comment]
Actually, this solution has nothing to do with the error. Another issue with a more elaborate title regarding this error was opened, please refer to it for the answer. Closing.
